shamblett/coap

lib/src/codec/encoders/coap_message_encoder18.dart

This PR resolves #47 by using the correct getter for block options during encoding. See #47 for more context.

fix: use compressed bytes for block option encoding

---

README.md

This PR replaces two http links in the README file with https ones which should increase the package score on pub.dev by five points to the maximum value of 120 (for native packages, that is).

chore: replace http links with https in README

---

lib/src/coap_message.dart
lib/src/coap_option.dart
lib/src/coap_option_type.dart
lib/src/codec/encoders/coap_message_encoder_rfc7252.dart
test/coap_option_test.dart

This PR cleans up the project by removing a number of option definitions that have become obsolete in later drafts and RFC 7252.

fix: remove obsolete CoAP options

---

README.md
lib/src/coap_code.dart
lib/src/coap_link_format.dart
lib/src/coap_option.dart
lib/src/observe/coap_observe_notification_orderer.dart
lib/src/specification/rfcs/coap_rfc7252.dart

This PR updates the documentation and replaces draft references with RFC numbers where needed.

docs: replace draft references with RFC numbers

---

lib/coap.dart
lib/src/channel/coap_network_udp.dart
lib/src/coap_request.dart
lib/src/net/coap_matcher.dart
lib/src/net/coap_multicast_exchange.dart
lib/src/stack/coap_layer_stack.dart

This PR applies a couple of fixes/changes to the project in order to make it possible to use simple (i. e. non-blockwise) multicast requests. To achieve this, multicast requests are no longer being able to be sent as confirmable messages (c. f. [RFC 7252, section 8.1](https://datatracker.ietf.org/doc/html/rfc7252#section-8.1)). Instead, all confirmable multicasts requests are converted to non-confirmable ones. Furthermore, multicast requests are no longer being labelled as complete after the first response and multiple responses no longer marked as duplicates.
I guess the solution is probably not perfect yet (and does not resolve #55 yet), but I guess it is a step into the right direction. Feedback is highly appreciated :)

fix: apply fixes to basic multicast scenario

---

lib/src/channel/coap_inetwork.dart
lib/src/channel/coap_network_udp.dart
lib/src/channel/coap_udp_channel.dart
lib/src/net/coap_client_message_deliverer.dart
lib/src/net/coap_exchange.dart
lib/src/stack/coap_blockwise_layer.dart

This PR fixes #55 by adding a method to the blockwise layer that converts multicast to unicast requests during blockwise transfer. To do so, some networking methods are adjusted to be able to retrieve the source address from responses and to provide a different address than the initial one for requests.

fix: switch to unicast for blockwise transfer after multicast request

---

example/hello_resource.dart
example/ping.dart
example/post_create_resource.dart
lib/src/channel/coap_udp_channel.dart

Using the library, I noticed that you cannot reuse the same or even a different client for requests to the same endpoint once the first client has been closed. I discovered that this is the case because a closed `CoapUDPChannel` was not being removed from the static list of networks in the `CoapNetworkManagement` class, yet. This PR fixes this issue.
Doing so, I noticed that calling `exit(0)` in some examples is not necessary anymore after the client has been closed. The remaining examples still need the `exit(0)` call, though.

fix: remove closed UDP channels from CoapNetworkManagement

---

lib/src/net/coap_internet_address.dart

This change fixes an issue raised by pana that currently prevents the package from getting the full score on [pub.dev](https://pub.dev/packages/coap/score), if I see it correctly. It simply adds an override for the `hashCode` getter in the `CoapInternetAddress` class.
Similar to the overridden `=` operator, the hash code is calculated by combining the hashes of the `address` and the `bindAddress`.

fix: override hashCode in CoapInternetAddress

---

lib/src/stack/coap_blockwise_layer.dart

For blockwise transfers, `_findRequestBlockStatus` is called, which in turn calls `_prepareBlockCleanup`. Once blockwise requests complete, I take it the scheduled block cleanup has to be terminated by calling `_clearBlockCleanup`? This prevents false-positive timeouts on successfully completed block requests and responses.
Verified that the problem exists for both block1 requests and block2 responses, and that this PR fixes those issues. The reason it doesn't show in the examples is because they are terminated before the timeout. Hope my fixes made their way to the right place, new to this code base :)
A nitpick which this PR doesn't address is that block1 timeouts provoked in this way are reported as block2 timeouts. Since the timeouts themselves are a bug, it could just be an artifact …

Fix false-positive timeouts

---

analysis_options.yaml
lib/src/net/coap_endpoint.dart
lib/src/network/coap_inetwork.dart
lib/src/network/coap_network_udp.dart

[Experimenting with adding CoAPS support](https://github.com/shamblett/coap/compare/issue75...namib-project:dtls-new-api?expand=1) to the library, I noticed that my implementation requires an asynchronous `send` method as it might need to reconnect to a server. This PR therefore changes its return type from `int` to `Future<int>`.
This change does not have an effect on the current state of the library, as sending UDP datagrams is a synchronous operation, but lays the foundation for future additions in general. I suppose that TCP might  make use of this change as well.

feat: change return type of `send` method to `Future<int>`

---

lib/src/coap_option_type.dart
lib/src/network/coap_inetwork.dart

I noticed that currently the messages of the newly defined Exceptions are not displayed when they are thrown, because the `toString()` method is not overridden. This PR fixes the issue.

fix: override toString() in Exception classes

---

example/cancel_request.dart
example/delete_resource.dart
example/discover_resources.dart
example/get_blockwise.dart
example/get_max_retransmit.dart
example/get_observe_async.dart
example/get_resource.dart
example/get_resource_secure.dart
example/log_events.dart
example/multi_client.dart
example/ping.dart
example/post_blockwise.dart
example/post_resource.dart
example/put_resource.dart
example/sync_vs_async.dart
lib/coap.dart
lib/src/coap_client.dart
lib/src/coap_option_type.dart
lib/src/exceptions/coap_request_exception.dart
lib/src/network/coap_inetwork.dart

This PR is supposed to be merged after #90 and #91.
Working with the new API, I noticed that handling the possible `null` value that is returned when a request fails is not as convenient as when the request simply throws an Exception. This PR therefore proposes yet another API change by introducing two new Exceptions for cancelled and timed out requests, allowing these two cases of errors to be handled differently.
This behavior should also be more similar to the `http` package's client, which also does not return `null` but throws an exception on failed requests (see, for instance, [here](https://github.com/dart-lang/http/blob/87d43798ae0fe7264ecda9d0dbc3e491a2abab65/lib/src/io_client.dart#L26)).
CC @JosefWN

feat!: let failed requests throw Exceptions instead of returning null

---

lib/src/coap_option.dart
lib/src/codec/decoders/coap_message_decoder_rfc7252.dart
test/coap_message_api_test.dart
test/coap_option_test.dart

This PR applies some minor refactorings to the creation of CoapOptions, getting rid of the `ignore: prefer_constructors_over_static_methods` comment.

refactor: refactor CoapOption creation using factory constructors

---

lib/src/coap_option.dart
lib/src/coap_option_type.dart
lib/src/stack/coap_chain.dart

In the current Dart version, using a `name` field in an enhanced enum (as we currently do in the `OptionType` enum) causes a segmentation fault (c.f., https://github.com/dart-lang/sdk/issues/49296). Although this will be fixed in the next version, this PR simply changes the identifier of the name in question as a workaround to avoid segfaults.

fix: change identifier of OptionType name field

---

lib/coap.dart

I noticed that the defined multicast addresses are another file that should be exported. This PR adjusts the top-level `coap.dart` file accordingly.

feat: expose `coap_defined_address.dart`

---

lib/src/coap_client.dart
lib/src/coap_media_type.dart
lib/src/coap_message.dart
lib/src/coap_option.dart
lib/src/stack/coap_blockwise_status.dart
test/coap_base_class_test.dart
test/coap_message_encode_decode_test.dart

This reworks the Content-Format registry as an enhanced enum and adds the missing values from the IANA CoAP [Content-Formats registry](https://www.iana.org/assignments/core-parameters/core-parameters.xhtml#content-formats), also supporting those with parameters and encoding values.
CC @JosefWN

refactor!: use enhanced enum for ContentMediaType

---

lib/src/coap_media_type.dart

Using the new Content-Format implementation, I noticed that there are a few entries from the [IANA registry](https://www.iana.org/assignments/core-parameters/core-parameters.xhtml) missing. This PR closes the gap. I also noticed a small bug with regard to one numeric value that is also fixed.

Close gaps in Content-Format registry

---

lib/src/coap_empty_message.dart
lib/src/coap_request.dart
lib/src/coap_response.dart

The named constructors were not setting `CoapCode.empty`, converted to factory constructors to re-use the main constructor.
EDIT: Also had to downgrade a couple of dependencies to get things to work with the latest version of Flutter, a bit of an annoyance that they are not up to speed.

Fixes issue #107

---

example/get_resource_secure.dart
lib/src/network/credentials/psk_credentials.dart
pubspec.yaml

Due to the fact that not all PSK credentials consist of UTF-8 strings, the API in dart_tinydtls to accept `Uint8List`s as parameters instead of `String`s.
This PR updates the CoAP API accordingly, while also upgrading dart_tinydtls to the latest version, which also fixes some issues with connections that are closed by a peer due to an error.

fix!: upgrade `dart_tinydtls`, use `Uint8List` for `PskCredentials` instead of `String`

---

lib/src/coap_client.dart
lib/src/coap_code.dart
lib/src/coap_empty_message.dart
lib/src/coap_message.dart
lib/src/coap_message_type.dart
lib/src/coap_request.dart
lib/src/coap_response.dart
lib/src/codec/decoders/coap_message_decoder.dart
lib/src/codec/decoders/coap_message_decoder_rfc7252.dart
lib/src/codec/encoders/coap_message_encoder.dart
lib/src/codec/encoders/coap_message_encoder_rfc7252.dart
lib/src/net/coap_exchange.dart
lib/src/stack/coap_blockwise_layer.dart
lib/src/stack/coap_observe_layer.dart
lib/src/stack/coap_reliability_layer.dart
test/coap_message_api_test.dart
test/coap_message_encode_decode_test.dart

This PR refactors the `CoapCode` and `CoapMessageType` classes as enhanced enums (also see #80), making the code more concise and readable. The changes also make it easier to add more `CoapCode`s in the future. The PR itself adds a few missing `CoapCode`s from the IANA registry, including the new method codes `FETCH`, `PATCH`, and `iPATCH`.
CC @JosefWN

refactor!: rework `CoapCode` and `CoapMessageType` as enhanced enums

---

lib/src/coap_option_type.dart

This PR applies a minor rework to the CoAP option code registry, simplifying the matching of codes to enum values. It also adds the remaining missing option codes from the IANA registry.

feat: refactor option number decoding, add missing option codes

---

lib/src/coap_defined_address.dart

This PR adds the multicast addresses defined for CoRE Resource Directories in [RFC 9176, section 9.5](https://datatracker.ietf.org/doc/html/rfc9176#section-9.5) to the library. This way it becomes easier to find Directories and perform discovery, especially when using the newly added parameters from #119 (once it is ready and merged).

feat: add CoRE RD (RFC 9176) multicast addresses

---

lib/src/coap_message.dart
test/coap_message_api_test.dart

Interacting with other CoAP libraries, we noticed in my project that URI paths seem to not be converted into options correctly. In particular, it seems as if empty URI path segments are supposed to be converted into empty URI-path options. Currently, these empty segments are removed from the URI path completely.
This PR adjusts the corresponding creation method accordingly, which should also make the library's behavior more consistent with [section 6.4 of RFC 7252](https://datatracker.ietf.org/doc/html/rfc7252#section-6.4).

fix: allow empty URI path segments in requests

---

lib/src/coap_client.dart
lib/src/coap_message.dart
test/coap_message_api_test.dart

At the moment, both for the Accept and the Content-Format option, a default value of 0 (`text/plain; charset=utf-8`) is set for requests. This is a bit at odds with the CoAP specification, which assumes no default value for these two options and can lead to unintended side effects if a server rejects certain accept values (but would allow requests with no accept option set).
Therefore, this PR proposes removing the default values from the creation methods, giving full control to the library users.

fix: don't set default Accept and Content-Format options

---

.github/workflows/ci.yml

This PR adds a small improvement to the CI, making it run not only on Linux but also on macOS and Windows.

chore: also run CI on macOS and Windows

---

lib/src/coap_media_type.dart

This PR refactors the creation of `CoapMediaType`s from numeric values by using a `HashMap` as a registry instead of iterating over all values. This should somewhat increase the performance, as `CoapMediaType`s can now be determined with constant instead of linear complexity.

refactor: use HashMap for "parsing" numeric Content-Formats

---

README.md
lib/src/coap_client.dart
lib/src/coap_request.dart

This is a relatively simple PR that adds support for the newly defined `FETCH`, `PATCH`, and `iPATCH` methods to the `CoapClient`  and `CoapRequest` classes. It could be included in the 5.0.0 release but we might as well integrate it in 5.1.0.
CC @JosefWN

feat: add constructors and client methods for new CoAP methods

---

example/get_observe_async.dart
example/get_resource_multicast.dart
lib/src/coap_client.dart
lib/src/coap_message.dart
lib/src/coap_observe_client_relation.dart
lib/src/stack/coap_reliability_layer.dart

Thinking about a more elegant solution for performing multicast requests, I came up with introducing a special `sendStream` method on the client, which does not return a single `Future<CoapResponse>` but a `Stream` of responses library users can decide to listen to.
With this new API present, I realized that other aspects of the client could be refactored, too, making certain aspects of the client a bit more elegant. This includes the `CoapObserveClientRelation` class, which I refactored into an extension of the `Stream` class, increasing its usability.
All in all, I am quite happy with this new approach which should not only improve the usability for multicast scenarios but of the library as a whole.

feat!: introcuce `_sendWithStreamResponse` and `sendMulticast` methods, refactor send and observe implementations

---

lib/src/codec/udp/message_decoder.dart

As uncovered in #132, there is currently a bug when it comes to the CoAP Ping example, introduced by #127. After doing some research, I noticed that this is caused by an incorrect handling of empty message tokens, which are currently identified as invalid. This PR applies a simple fix by returning an empty buffer if a token length of zero should be encountered, resolving not only the ping issue but also other unintended side effects.

fix: fix parsing of empty tokens

---

lib/src/coap_client.dart
lib/src/event/coap_event_bus.dart

This PR provides a solution for the bug uncovered by @shamblett in https://github.com/shamblett/coap/issues/132#issuecomment-1288068964. The filtering logic is now moved inside a `StreamTransformer` object, which adds exceptions to the stream on timeout or cancellation. Similar to your suggestion in the issue, the relevant events are pre-filtered using a new `CoapCompletionEvent` interface that is "implemented" by the `CoapResponse`, `CoapRequestTimeoutException`, and `CoapRequestCancellationException` classes. Lastly, the PR applies minor refactoring to the matching of the original request and relevant responses.

Fix timeout/max retransmission handling

---

lib/src/coap_client.dart

In the context of #138, I noticed that the `CoapRequestTimeoutException` is currently a bit broken and does not display the correct number of retransmits (instead, it always reports 0 retransmits). This PR provides a simple fix.

fix: report correct retransmit count on timeout

---

lib/src/coap_constants.dart

This PR should partly resolve #138, adjusting both `maxRetransmit` and `ackTimeout` to the default values specified in [RFC 7252, section 4.8](https://www.rfc-editor.org/rfc/rfc7252#section-4.8).
There might be further possible adjustments to default config values and their handling that could be made in follow-up PRs, but for now this should deal with the most important issue.

fix: adjust default config values

---

example/get_resource_multicast.dart
lib/src/multicast_address.dart

This PR proposes a slight API improvement for the `MulticastAddress` enum. Overriding the `toString` method, the proposed changes make it a bit more convenient to use the enum values in the context of string interpolation.

feat: override toString() method of MulticastAddress

---

lib/src/coap_client.dart
lib/src/coap_media_type.dart
lib/src/coap_message.dart
lib/src/option/integer_option.dart
lib/src/option/option.dart
lib/src/option/oscore_option.dart
test/coap_base_class_test.dart

This PR addresses some of the TODOs mentioned in #140 and a couple of minor linting issues.
As part of this PR, the `isPrintable` method is removed from the `CoapMediaType` enum as it did not fulfill a real purpose IMHO.

Address Todos

---

example/get_observe_async.dart
example/sync_vs_async.dart
lib/src/coap_client.dart
lib/src/coap_code.dart
lib/src/coap_empty_message.dart
lib/src/coap_message.dart
lib/src/coap_request.dart
lib/src/coap_response.dart
lib/src/codec/udp/message_decoder.dart
lib/src/codec/udp/message_encoder.dart
lib/src/stack/layers/blockwise.dart
test/coap_datagram_read_write_test.dart
test/coap_message_api_test.dart
test/coap_message_encode_decode_test.dart

Revisiting the current CoapCode implementation, I got the impression that the APIs for creating new requests and responses could be improved to leave less room for potential errors by introducing separate enums for request methods as well as response and signaling codes. This PR implements this change, creating a `RequestMethod`, a `ResponseCode`, and a `SignalingCode` enum in the process, while turning the `CoapCode` enum into an immutable class that carries the numeric values.
Due to the fact that the empty messages sent during the CoAP ping are currently handled as requests, I could not remove the `empty` value from the `RequestMethod` enum. I added a TODO that this value should be revisited during future reworks of the internal API. However, maybe it could also be left as is.
Since …

refactor!: refactor CoapCodes as separate enums

---

lib/src/network/coap_network_openssl.dart

In the OpenSSL network, it seems to me that currently the network is not properly cleaned up if the initial connect should time out, causing the CoAP client to hang. This PR adjusts the connect behavior, calling `close` if a timeout should happen and rethrowing the `TimeoutException`.

fix(openssl): clean up network on timeout exception

---

lib/src/coap_client.dart

This PR contains the fix from https://github.com/shamblett/coap/issues/153#issuecomment-1396977877.
Potentially resolves #153.
CC @vincent-iQontrol

fix: don't call completer on timeout after reconnect

---

lib/src/coap_message.dart
lib/src/coap_request.dart
lib/src/coap_response.dart
lib/src/option/string_option.dart
lib/src/stack/layers/observe.dart
test/coap_message_api_test.dart
test/coap_message_encode_decode_test.dart

This PR applies some fixes to the URI options (regarding percent-encoding) and resolves a problem with the String option encoding.
It also resolves a couple of TODOs from #142.

fix: apply proper percent encoding to URI options

---

lib/src/coap_message.dart
lib/src/coap_request.dart
lib/src/coap_response.dart
lib/src/codec/udp/message_encoder.dart
lib/src/option/string_option.dart
lib/src/stack/layers/observe.dart
test/coap_message_api_test.dart
test/coap_message_encode_decode_test.dart

Reading through the RFC, I noticed that the skipping of the Uri-Host and Uri-Port options is not necessary if their values are not the default. Including them as proposed in this PR makes it easier to determine where a request was sent to, as illustrated in the following Wireshark screenshot:
(This PR depends on #157 and should only be merged afterwards.)

feat: only skip host and port options if non-default

---

lib/src/codec/udp/message_decoder.dart
lib/src/codec/udp/message_encoder.dart
lib/src/option/integer_option.dart
test/coap_option_test.dart

I've got the impression that the handling of endianness in the `IntegerOption`s could already be fine by now. Therefore, I wanted to propose removing the two TODOs within the `IntegerOption` class. I am not entirely sure about big endian platforms, though. However, doing some manual testing did not reveal a problem so far.
Do you think the current state of this kind of option is fine, @JosefWN? Or do you think we should add some more formal testing in this regard?

refactor: properly handle network byte order in IntegerOption

---

lib/src/network/coap_network_openssl.dart
pubspec.yaml

This PR bumps `dtls2` to version 0.11.0 which solves a problem that could occur if the use of PSK ciphers suites was indicated with no PSK callback defined. In this case (e.g., in the `get_resource_secure` example when commenting out the callback argument) a segmentation fault could occur with not further information. The new version fixes this problem.
To be able to properly handle all exceptions that can occur during the connection establishment, the `on` clause now captures all `Exception` objects, closes the client, and rethrows them.

fix: bump dtls2 to version 0.11.0, handle all exceptions during connect

---

lib/src/option/coap_block_option.dart
lib/src/option/empty_option.dart
lib/src/option/integer_option.dart
lib/src/option/opaque_option.dart
lib/src/option/option.dart
lib/src/option/oscore_option.dart
lib/src/option/string_option.dart

This PR proposes a trivial refactoring, turning the interfaces for identifying OSCORE class into more idiomatic Mixins.

refactor: replace OSCORE Interfaces with Mixins

---

.github/workflows/ci.yml
.gitignore

This PR adjusts the CI pipeline slightly so that it generates code coverage reports when testing. This would make it possible to visualize coverage of the code base using a provider such as codecov or coveralls in a next step.

chore: let CI generate code coverage reports

---

.github/workflows/ci.yml
README.md

As discussed in #171, this PR adds an upload step for codecov.io which enables code coverage visualization features. ~~For this to properly work, adding a `CODECOV_TOKEN` as a secret would also be needed, I think.~~
Using the [codecov GitHub app](https://github.com/marketplace/codecov), we could integrate code coverage report into PRs, which I quite like since they create an incentive to provide additional tests. Not everyone seems to be a fan of them, though.
Edit: Seems as if the bot is working already :)

chore(ci): add codecov upload step

---

example/cancel_request.dart
example/get_max_retransmit.dart
example/get_observe_async.dart
example/get_resource_multicast.dart
example/post_resource.dart
lib/src/coap_client.dart
lib/src/coap_message.dart
lib/src/coap_observe_client_relation.dart
lib/src/coap_request.dart
lib/src/coap_response.dart
lib/src/codec/udp/message_decoder.dart
lib/src/codec/udp/message_encoder.dart
lib/src/network/coap_network_openssl.dart
lib/src/network/coap_network_udp.dart
lib/src/option/option.dart
lib/src/option/uri_converters.dart
lib/src/stack/layers/blockwise.dart
lib/src/stack/layers/observe.dart
test/coap_datagram_read_write_test.dart
test/coap_message_api_test.dart
test/coap_message_encode_decode_test.dart

This PR proposes a rework of the `uri` field within the `CoapRequest` class. Before, the `Uri` was constructed by using individual `Uri-Host`, `Uri-Path`, `Uri-Port`, and `Uri-Query` options.
However, I noticed that a request's URI can be set in a much simpler way by simply turning it into a regular field which can then be converted into and from individual URI component options. This enabled me to implement the algorithms described in [section 6.4](https://www.rfc-editor.org/rfc/rfc7252.html#section-6.4) and [section 6.5 of RFC 7252](https://www.rfc-editor.org/rfc/rfc7252.html#section-6.5) in two functions, which makes debugging a bit easier. With these changes, the conversion should now be RFC-compliant (again) and slightly easier to maintain.
The new approach also allowed/incentivized …

feat!: rework URI handling for CoAP requests and responses

---

lib/src/stack/layers/blockwise.dart

#169 introduced a small bug that broke blockwise transfer, since request URIs were copied twice. This PR provides a quick fix that should be followed up by a more elegant solution in the future, though.

fix: fix blockwise transfer

---

lib/src/option/coap_option_type.dart

As a first step to implementing a caching mechanism, this PR adds checks for the `NoCacheKey` property to the `OptionType` enum which can be derived from an option code.

feat: add cache key checks to OptionType enum

---

lib/src/option/coap_option_type.dart
lib/src/option/integer_option.dart
test/coap_option_test.dart

I understood only recently how the two options specified by OCF are supposed to work. This PR updates the API for creating and reading out these options, adds some documentation, and fixes a minor issue in the `UnknownOptionException` class.

feat: improve OCF version options API

---

example/get_resource_secure.dart
lib/src/network/credentials/psk_credentials.dart
pubspec.yaml

This PR updates the `dtls2` dependency and incorporates some (unfortunately breaking) API changes.

chore!: update dtls2, update DTLS PSK API

---

pubspec.yaml

This PR updates the `dtls2` dependency to the latest version.

chore(deps): update dtls2 to version 0.13.4

---

lib/src/coap_client.dart
lib/src/coap_message.dart
lib/src/coap_request.dart
lib/src/coap_response.dart
lib/src/stack/layers/blockwise.dart
test/coap_message_api_test.dart
test/coap_message_encode_decode_test.dart

This PR makes a couple of improvements to the request API by adding a `query` parameter, adding payload-related parameters to the `fetch` method (which actually is the main USP of this request method), and changing the type of the payload parameter from `Uint8Buffer` to `Iterable<int>`, increasing the number of possible input types (by including types like `Uint8List` or `List<int>`).
The PR also applies some additional clean up, getting rid of some getters and setters that are not actually needed.

Improve request APIs

---

pubspec.yaml

I just released a new version of `dtls2` with a few fixes. This PR incorporates updates the dependency here.

chore: update dtls2 to version 0.15.0

---

analysis_options.yaml
lib/src/coap_client.dart
lib/src/event/coap_event_bus.dart
lib/src/exceptions/coap_request_exception.dart
lib/src/network/coap_inetwork.dart
lib/src/option/coap_block_option.dart
lib/src/option/coap_option_type.dart
lib/src/stack/layers/reliability.dart
pubspec.yaml

Solves https://github.com/shamblett/coap/issues/187
Linted & upgraded deps while I was at it. Currently running 10k requests and watching out for leaks, but looking good after 1000 requests...
I don't have a good setup to test multicast requests right now, but they should still work 🤞🏻
UPDATE: Okay, done running the polling, no leaks observed!

Polling causes memory leak by retaining request objects indefinitely

---

pubspec.yaml

This PR updates the dtls2 package to the latest version.
There are currently a couple of issues when trying to use the CoAPS example with newer versions of DTLS because they have deprecated a number of cipher suites, including the mandatory one for CoAP (`TLS_PSK_WITH_AES_128_CCM_8`), making it necessary to explicitly state that you want to them, which is a bit annoying. I will create another patch version soon that will address this issue and make the package usable in this context again.

Update dtls2 package to version 0.17.0

---

lib/src/coap_client.dart

This PR should fix #190.
I noticed that the `onCancel` callback that has been added to the `observe` method in #188 was called a bit too early to allow for the delivery of incoming responses. This PR adds a boolean variable to track if the preparation of the `CoapObserveClientRelation` is already done, preventing the callback from early invocation.

fix: prevent premature cancellation of observerelation

---

lib/src/coap_client.dart
lib/src/coap_observe_client_relation.dart

PR related to issue #193
To prevent the check from blocking the function until after the first response is received, I created a method within the `CoapObserveClientRelation` called `checkObserve` that checks for the observe flag upon receiving the first response. This approach eliminates the need for await, ensuring that the `CoapObserveClientRelation` object already has our `onData` method when the first response is received.

Fix: first observe response not being handled

---

.github/workflows/ci.yml

As mentioned in #189, there is currently an issue with the CI when it is running under Dart 3.4.0 and Windows. This issue adds a workaround that lets the CI fall back to 3.3.0 under Windows so that the respective job does not fail anymore due to a timeout. As soon as the issue has been fixed upstream, this change can be reverted.

ci: add workaround for failing CI on Windows

---

lib/coap.dart
lib/src/coap_config.dart
lib/src/network/coap_network_openssl.dart
pubspec.yaml

This PR updates the `dtls2` package to the latest version. Since there have been API changes in `dtls2` regarding the handling of certificates, the relevant parts of the API for this package are modified accordingly and the certificate classes in question are re-exported.
The main benefit of this change is now that you are able to provide root certificates that can also be in PEM format, making the use of DTLS in PKI mode a bit more versatile and the API itself clearer. However, as there are API changes involved, they have to be considered breaking changes.

chore!: update dtls2 package to version 0.18.0

---

.github/workflows/ci.yml

I noticed a minor leftover of the workaround introduced by https://github.com/shamblett/coap/pull/191, which can now be safely removed.

ci: remove unused matrix.sdk variable

---

lib/src/coap_config.dart

This is another trivial PR removing a leftover import that has become unnecessary after the merge of #200. Merging this one will grant the package the full score in the "Pass static analysis" category again.

chore: remove unused import

---

example/get_resource_secure.dart
lib/src/coap_config.dart
lib/src/network/coap_inetwork.dart
lib/src/network/coap_network_openssl.dart

As discussed in https://github.com/shamblett/coap/pull/200, this PR adds the ability to override the security level used by OpenSSL.  This allows for still using cipher suites like `TLS_PSK_WITH_AES_128_CCM_8` that must be supported by CoAP implementations (see [section 9.1.3.1](https://datatracker.ietf.org/doc/html/rfc7252#section-9.1.3.1) of RFC 7252), as more recent versions of OpenSSL are not allowing them to be used anymore without lowering the security level.
The DTLS example is adjusted accordingly so that it now works again.

Allow for overriding the OpenSSL security level
